import { GridColDef} from '@mui/x-data-grid';

export const finesColumns: GridColDef[] = [
     { field: 'id', headerName: 'ID', width: 80, hide: true, align: 'right' },
     { field: 'codigo', headerName: 'Código', width: 130, align: 'left', headerAlign: 'left' },
     { field: 'placa', headerName: 'Placa', width: 130 },
     { field: 'status', headerName: 'Satus', width: 130, align: 'left', headerAlign: 'left' },
     { field: 'dataInfracao', headerName: 'Data da infração', width: 170},
     { field: 'situacao', headerName: 'Situação', width: 130, align: 'left', headerAlign: 'left' },
     { field: 'cidade', headerName: 'Cidade', width: 130, align: 'left', headerAlign: 'left' },
     { field: 'valorBoleto', headerName: 'Valor do Boleto', width: 130, align: 'left', headerAlign: 'left'},
     { field: 'dataVencimentoBoleto', headerName: 'Data de Vencimento', width: 180, align: 'left', headerAlign: 'right' },
     { field: 'descricao', headerName: 'Descrição', width: 130, align: 'left', headerAlign: 'left' },
     { field: 'endereco', headerName: 'Endereço', width: 100, align: 'left', headerAlign: 'left' },
     { field: 'valor', headerName: 'Valor', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'horaInfracao', headerName: 'Hora da Infração', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'artigo', headerName: 'Artigo', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'codigoBarras', headerName: 'Código de Barras', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'orgao', headerName: 'Orgão', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'renavam', headerName: 'Renavam', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'ait', headerName: 'AIT', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'id_situacao', headerName: 'Id Situação', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'pontuacao', headerName: 'Pontuação', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'velocidadeMedida', headerName: 'Velocidade', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'velocidadeRegulamentada', headerName: 'Velocidade Regular', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'autoInfracao2', headerName: 'Auto Infracional', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'uf', headerName: 'UF', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'datahoraInfracaoUTC', headerName: 'Data/Hora (Infração)', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'nicAutoInfracaoOriginario', headerName: 'NIC - Auto Infração Originário', width: 130, hide: true, align: 'left', headerAlign: 'left' },
     { field: 'aiipmulta', headerName: 'AIIP - Multa', width: 130, hide: true, align: 'left', headerAlign: 'left' },
 
    ];