on:
  pull_request_review:
    types: [submite]
    branches: [development]
    
jobs:
  CI:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3.1.0
      
      - name: Login on Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build  and Push Image Docker
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            devpolatto/smartfleet:v1.0.${{github.run_number}}
            devpolatto/smartfleet:latest
    
  CD:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
